### ISSUE TITLE
Toasts aren't working on iOS devices

### ISSUE THREAD

**Issue by starfreck** [kuasha420/react-native-paper-toast#10]
Toasts aren't working on iOS devices. It only shows a very small toast banner with no message inside. It works fine with Android.

**Comment by pauloeduardoferreira** [comment]
same here...

**Comment by QianZhongWang** [comment]
same here...

**Comment by deeeed** [comment]
You need to add a width in the snackbarStyle.
I patched it locally by setting it in the `common` style.
```tsx
const common: ViewStyle = {
  borderRadius: 3,
  minWidth: 250,
};
```

**Comment by deemyboy** [comment]
@deeeed where did you write that code?

**Comment by deemyboy** [comment]
if you remove your react-native-paper-toast and then use either of these

yarn:
 yarn add https://github.com/kuasha420/react-native-paper-toast#3b474847a5275ed586a41d283301986f23fe8b90

npm:
 npm install https://github.com/kuasha420/react-native-paper-toast#3b474847a5275ed586a41d283301986f23fe8b90

you will get the ability to add 3 new properties to the toast - snackbarStyle, messageStyle and messageContainerStyle

I'm using 2 of the new properties and the 'minWidth' fixes the very thin green snackbar (no text visible) and the 'flexDirection: 'row'' fixes the stacked layout (Icon above the text - now it's inline)

toaster.show({ type: type, message: message, snackbarStyle: { minWidth: 300 }, messageContainerStyle: { flex: 1, flexDirection: 'row' } });

**Comment by kuasha420** [comment]
Fixed in latest release.
