### ISSUE TITLE
Type error on ToastProvider

### ISSUE THREAD

**Issue by bm2dev** [kuasha420/react-native-paper-toast#9]
The error is on the "children" prop, someone already solved this issue and made a pull request.

**Comment by nel-sam** [comment]
@kuasha420 When can we expect to see the latest released on NPM?

**Comment by abretonc7s** [comment]
+1, any change on that?

**Comment by EmilyRagan** [comment]
@kuasha420 Will the fix for this type error be released to NPM soon?

**Comment by deemyboy** [comment]
+1

**Comment by kuasha420** [comment]
Fixed in latest release.
